name = "QGYBJ"
uuid = "961669e7-04c5-4537-a859-b8655c92fdd1"
license = "MIT"
authors = ["Subhajit Kar <subhajitkar19@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PencilArrays = "0e08944d-e94e-41b1-9406-dcf66b6a9571"
PencilFFTs = "ceb66b5b-6631-4ecd-8d2a-fe91a1bfaa04"

[extensions]
QGYBJMPIExt = ["MPI", "PencilArrays", "PencilFFTs"]

[compat]
FFTW = "1.9"
MPI = "0.20"
PencilArrays = "0.19"
PencilFFTs = "0.15"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
