name = "QGYBJ"
uuid = "961669e7-04c5-4537-a859-b8655c92fdd1"
license = "MIT"
authors = ["Subhajit Kar <subhajitkar19@gmail.com>"]
version = "0.1.0"

[deps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
NCDatasets = "0.14.8"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
