name = "QGYBJ"
uuid = "961669e7-04c5-4537-a859-b8655c92fdd1"
authors = ["Subhajit Kar <subhajitkar19@gmail.com>"]
version = "0.1.0"
license = "MIT"

[compat]
julia = "1.9"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c0909f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
